---
abstract: 'Catmandu tools to communicate with DBI based interfaces'
author:
  - 'Nicolas Franck'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build::Tiny: 0.038
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-DBI
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: 0.2003
  DBI: 1.630
  Moo: 1.000003
  namespace::clean: 0.24
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-DBI/issues
  homepage: https://github.com/LibreCat/Catmandu-DBI
  repository: https://github.com/LibreCat/Catmandu-DBI.git
version: 0.011
x_contributors:
  - 'Nicolas Franck <nicolas.franck@ugent.be>'
